version: "3.9"
services:
  mysql:
    container_name: mysql_container
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - '3306:3306'
